# Generated by Django 5.2.12 on 2026-03-09 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('category', models.CharField(choices=[('fruit', 'Fruta'), ('vegetables', 'Verduras'), ('meat', 'Carne'), ('fish', 'Pescado y marisco'), ('dairy', 'Lácteos'), ('eggs', 'Huevos'), ('bread', 'Panadería'), ('cereals', 'Cereales y desayuno'), ('pasta_rice', 'Pasta y arroz'), ('legumes', 'Legumbres'), ('frozen', 'Congelados'), ('canned', 'Conservas'), ('snacks', 'Snacks y aperitivos'), ('sweets', 'Dulces y repostería'), ('sauces', 'Salsas y condimentos'), ('spices', 'Especias'), ('oil_vinegar', 'Aceite y vinagre'), ('drinks', 'Bebidas'), ('alcohol', 'Alcohol'), ('cleaning', 'Limpieza del hogar'), ('hygiene', 'Higiene personal'), ('baby', 'Bebé'), ('pets', 'Mascotas'), ('other', 'Otros')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('unit', models.CharField(choices=[('unit', 'Unidades'), ('kg', 'Kilogramos'), ('g', 'Gramos'), ('l', 'Litros'), ('ml', 'Mililitros')], default='unit', max_length=10)),
                ('picked_up', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ListaCompra.product')),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ListaCompra.shoppinglist')),
            ],
        ),
    ]
