# Generated by Django 5.2.12 on 2026-03-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ListaCompra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='shop',
            field=models.CharField(choices=[('mercadona', 'Mercadona'), ('alcampo', 'Alcampo'), ('sorli', 'Sorli'), ('esclat', 'Esclat'), ('bonpreusa', 'Bonpreu'), ('caprabo', 'Caprabo'), ('carrefour', 'Carrefour')], default='mercadona', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='shoppinglistitem',
            unique_together={('shopping_list', 'product')},
        ),
    ]
